#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

include $(MDF_PATH)/project.mk
#include $(IDF_PATH)/make/project.mk

