#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := $(notdir $(shell pwd))
#EXTRA_COMPONENT_DIRS := $(IDF_PATH)/esp-idf-lib/components
include $(MDF_PATH)/project.mk
